version: "3.3"
services:
  alerts:
    build: ./alerts
    volumes:
      - logs:/app/logs
  log-access:
    build: ./log-access
    volumes:
      - logs:/app/logs
    ports:
      - "80:8000"
volumes:
  logs: